#lang racket/base

(require rackunit rackunit/text-ui "../src/ch5.rkt")
(provide ch5-tests)

(define ch5-tests
  (test-suite
   "ch5 tests"
(check-equal? (rember* 'cup '((coffee) cup ((tea) cup) (and (hick)) cup))
              '((coffee) ((tea)) (and (hick))))
(check-equal? (insertR* 'roast 'chuck '((how much (wood))
                                        could
                                        ((a (wood) chuck))
                                        (((chuck)))
                                        (if (a) ((wood chuck)))
                                        could chuck wood))
              '((how much (wood))
                could
                ((a (wood) chuck roast))
                (((chuck roast)))
                (if (a) ((wood chuck roast)))
                could chuck roast wood))
(check-equal? (occur* 'banana '((banana)
                                (split ((((banana ice)))
                                        (cream (banana))
                                        sherbet))
                                (banana)
                                (bread)
                                (banana brandy)))
              5)
(check-equal? (subst* 'orange 'banana '((banana)
                                        (split ((((banana ice)))
                                                (cream (banana))
                                                sherbet))
                                        (banana)
                                        (bread)
                                        (banana brandy)))
              '((orange)
                (split ((((orange ice)))
                        (cream (orange))
                        sherbet))
                (orange)
                (bread)
                (orange brandy)))
(check-equal? (insertL* 'pecker 'chuck '((how much (wood))
                                         could
                                         ((a (wood) chuck))
                                         (((chuck)))
                                         (if (a) ((wood chuck)))
                                         could chuck wood))
              '((how much (wood))
                could
                ((a (wood) pecker chuck))
                (((pecker chuck)))
                (if (a) ((wood pecker chuck)))
                could pecker chuck wood))

(check-true (member* 'chips '((potato) (chips ((with) fish) (chips)))))

(check-equal? (leftmost '((potato (chips ((with) fish) (chips)))))
              'potato)
(check-equal? (leftmost '(((hot) (tuna (and))) cheese))
              'hot)
(check-true (eqlist? '(strawberry ice cream)
                     '(strawberry ice cream)))
(check-false (eqlist? '(strawberry ice cream)
                      '(strawberry cream ice)))
(check-false (eqlist? '(banana ((split)))
                      '((banana (split)))))
(check-false (eqlist? '(beef ((sausage)) (and (soda)))
                      '(beef ((salami)) (and (soda)))))
(check-true (eqlist? '(beef ((sausage)) (and (soda)))
                     '(beef ((sausage)) (and (soda)))))
(check-true (equal? '() '()))
(check-false (equal? 1 2))
(check-true (equal? 3 3))
(check-true (equal? '(a b (c d)) '(a b (c d))))
(check-true (equal? '(1 2 (3 c) ((words)) (more (((words)) a)))
                    '(1 2 (3 c) ((words)) (more (((words)) a)))))
(check-false (equal? '(1 2 (3 c) ((words)) (more (((words)) a)))
                     '(1 2 (3 c) ((words)) ((more) (((words)) a)))))))   